Repository zhmcclient/zhmc-ansible-modules, pull requests merged in 2020-11, with the labels that each got.

#183 Multiple changes to galaxy.xml.
  galaxy.yml
Labels: review needed

#189 Updated introduction section
  docs/source/conf.py
  docs/source/index.rst
  docs/source/intro.rst
Labels: review needed

#194 Updated README to fix syntax issues & badge links; Updated galaxy description
  README.md
  galaxy.yml
Labels: review needed

#216 Clarified distribution on Galaxy vs Pypi
  README.md
  docs_source/changes.rst
  docs_source/intro.rst
Labels: review needed

#200 Improvements in docs build
  Makefile
  docs/modules_support.html
  docs_source/conf.py
Labels: review needed

#219 Addressed TBDs in development section of docs
  docs_source/development.rst
Labels: review needed

#230 Publish docs for latest released version
  docs/development.html
  docs/searchindex.js
  docs_source/development.rst
Labels: review needed

#227 Fixed path names in introduction section
  docs/intro.html
  docs_source/intro.rst
Labels: review needed

#229 Added collection version to title; Added dev suffix to version
  docs/CONTRIBUTING.html
  docs/_static/documentation_options.js
  docs/all_modules.html
  docs/appendix.html
  docs/changes.html
  docs/development.html
  docs/genindex.html
  docs/index.html
  docs/intro.html
  docs/modules/zhmc_adapter.html
  docs/modules/zhmc_cpc.html
  docs/modules/zhmc_crypto_attachment.html
  docs/modules/zhmc_hba.html
  docs/modules/zhmc_nic.html
  docs/modules/zhmc_partition.html
  docs/modules/zhmc_storage_group.html
  docs/modules/zhmc_storage_group_attachment.html
  docs/modules/zhmc_storage_volume.html
  docs/modules/zhmc_user.html
  docs/modules/zhmc_virtual_function.html
  docs/objects.inv
  docs/search.html
  docs/searchindex.js
  docs_source/changes.rst
  docs_source/conf.py
  docs_source/development.rst
  docs_source/index.rst
  galaxy.yml
  setup.py
Labels: review needed

#244 Fixed missing collections property in example playbooks
  docs/changes.html
  docs/searchindex.js
  docs_source/changes.rst
  playbooks/attach_crypto.yml
  playbooks/attach_crypto_byname.yml
  playbooks/attach_storage_group.yml
  playbooks/create_hipersockets.yml
  playbooks/create_partition.yml
  playbooks/create_partition_crypto.yml
  playbooks/create_partition_sg.yml
  playbooks/create_storage_group.yml
  playbooks/create_storage_volume.yml
  playbooks/delete_hipersockets.yml
  playbooks/delete_partition.yml
  playbooks/delete_storage_group.yml
  playbooks/delete_storage_volume.yml
  playbooks/detach_crypto.yml
  playbooks/detach_storage_group.yml
  playbooks/facts_adapter.yml
  playbooks/facts_cpc.yml
  playbooks/facts_crypto.yml
  playbooks/facts_partition.yml
  playbooks/facts_storage_group.yml
  playbooks/facts_storage_group_attachment.yml
  playbooks/facts_storage_volume.yml
  playbooks/facts_user.yml
  playbooks/get_cpc_io.yml
  playbooks/set_adapter.yml
  playbooks/set_cpc.yml
  playbooks/set_matched_adapter.yml
  plugins/modules/zhmc_adapter.py
Labels: review needed

#251 Fixed the 'version_added' field in the module description
  docs/changes.html
  docs/searchindex.js
  docs_source/changes.rst
  plugins/modules/zhmc_adapter.py
  plugins/modules/zhmc_cpc.py
  plugins/modules/zhmc_crypto_attachment.py
  plugins/modules/zhmc_hba.py
  plugins/modules/zhmc_nic.py
  plugins/modules/zhmc_partition.py
  plugins/modules/zhmc_storage_group.py
  plugins/modules/zhmc_storage_group_attachment.py
  plugins/modules/zhmc_storage_volume.py
  plugins/modules/zhmc_user.py
  plugins/modules/zhmc_virtual_function.py
Labels: review needed

#246 Made faked_session parameter internal
  docs/modules/zhmc_adapter.html
  docs/modules/zhmc_cpc.html
  docs/modules/zhmc_crypto_attachment.html
  docs/modules/zhmc_hba.html
  docs/modules/zhmc_nic.html
  docs/modules/zhmc_partition.html
  docs/modules/zhmc_storage_group.html
  docs/modules/zhmc_storage_group_attachment.html
  docs/modules/zhmc_storage_volume.html
  docs/modules/zhmc_user.html
  docs/modules/zhmc_virtual_function.html
  docs/searchindex.js
  docs_source/modules/zhmc_adapter.rst
  docs_source/modules/zhmc_cpc.rst
  docs_source/modules/zhmc_crypto_attachment.rst
  docs_source/modules/zhmc_hba.rst
  docs_source/modules/zhmc_nic.rst
  docs_source/modules/zhmc_partition.rst
  docs_source/modules/zhmc_storage_group.rst
  docs_source/modules/zhmc_storage_group_attachment.rst
  docs_source/modules/zhmc_storage_volume.rst
  docs_source/modules/zhmc_user.rst
  docs_source/modules/zhmc_virtual_function.rst
  plugins/modules/zhmc_adapter.py
  plugins/modules/zhmc_cpc.py
  plugins/modules/zhmc_crypto_attachment.py
  plugins/modules/zhmc_hba.py
  plugins/modules/zhmc_nic.py
  plugins/modules/zhmc_partition.py
  plugins/modules/zhmc_storage_group.py
  plugins/modules/zhmc_storage_group_attachment.py
  plugins/modules/zhmc_storage_volume.py
  plugins/modules/zhmc_user.py
  plugins/modules/zhmc_virtual_function.py
  tests/end2end/test_zhmc_partition.py
  tests/end2end/test_zhmc_user.py
  tests/function/test_func_partition.py
  tests/unit/test_hba.py
  tests/unit/test_nic.py
  tests/unit/test_partition.py
  tests/unit/test_virtual_function.py
Labels: under work

#250 Improved return value docs and samples
  docs/changes.html
  docs/modules/zhmc_adapter.html
  docs/modules/zhmc_cpc.html
  docs/modules/zhmc_crypto_attachment.html
  docs/modules/zhmc_hba.html
  docs/modules/zhmc_nic.html
  docs/modules/zhmc_partition.html
  docs/modules/zhmc_storage_group.html
  docs/modules/zhmc_storage_group_attachment.html
  docs/modules/zhmc_storage_volume.html
  docs/modules/zhmc_user.html
  docs/modules/zhmc_virtual_function.html
  docs/searchindex.js
  docs_source/changes.rst
  docs_source/modules/zhmc_adapter.rst
  docs_source/modules/zhmc_cpc.rst
  docs_source/modules/zhmc_crypto_attachment.rst
  docs_source/modules/zhmc_hba.rst
  docs_source/modules/zhmc_nic.rst
  docs_source/modules/zhmc_partition.rst
  docs_source/modules/zhmc_storage_group.rst
  docs_source/modules/zhmc_storage_group_attachment.rst
  docs_source/modules/zhmc_storage_volume.rst
  docs_source/modules/zhmc_user.rst
  docs_source/modules/zhmc_virtual_function.rst
  plugins/modules/zhmc_adapter.py
  plugins/modules/zhmc_cpc.py
  plugins/modules/zhmc_crypto_attachment.py
  plugins/modules/zhmc_hba.py
  plugins/modules/zhmc_nic.py
  plugins/modules/zhmc_partition.py
  plugins/modules/zhmc_storage_group.py
  plugins/modules/zhmc_storage_group_attachment.py
  plugins/modules/zhmc_storage_volume.py
  plugins/modules/zhmc_user.py
  plugins/modules/zhmc_virtual_function.py
Labels: review needed

#276 Add a local docs build target.
  .gitignore
  Makefile
  docs/conf.py
  docs/development.rst
  galaxy.yml
Labels: update needed

#272 Excluded docs_build,.github from Galaxy archive
  galaxy.yml
Labels: review needed

#288 Added note that 1.0.0 is not released yet
  README.md
  docs/index.rst
Labels: review needed

#299 Fixed links to Z, LinuxONE, Installation on README page
  README.md
  docs/index.rst
Labels: roll back/fwd needed

#300 Renamed playbooks to sample_...
  README.md
  docs/playbooks.rst
  playbooks/sample_attach_crypto.yml
  playbooks/sample_attach_crypto_byname.yml
  playbooks/sample_attach_storage_group.yml
  playbooks/sample_create_hipersockets.yml
  playbooks/sample_create_partition.yml
  playbooks/sample_create_partition_crypto.yml
  playbooks/sample_create_partition_full.yml
  playbooks/sample_create_partition_sg.yml
  playbooks/sample_create_storage_group.yml
  playbooks/sample_create_storage_volume.yml
  playbooks/sample_delete_hipersockets.yml
  playbooks/sample_delete_partition.yml
  playbooks/sample_delete_storage_group.yml
  playbooks/sample_delete_storage_volume.yml
  playbooks/sample_detach_crypto.yml
  playbooks/sample_detach_storage_group.yml
  playbooks/sample_facts_adapter.yml
  playbooks/sample_facts_cpc.yml
  playbooks/sample_facts_crypto.yml
  playbooks/sample_facts_partition.yml
  playbooks/sample_facts_storage_group.yml
  playbooks/sample_facts_storage_group_attachment.yml
  playbooks/sample_facts_storage_volume.yml
  playbooks/sample_facts_user.yml
  playbooks/sample_get_cpc_io.md.j2
  playbooks/sample_get_cpc_io.yml
  playbooks/sample_set_adapter.yml
  playbooks/sample_set_cpc.yml
  playbooks/sample_set_matched_adapter.yml
Labels: review needed

#303 Added galaxy badge with version
  README.md
Labels: review needed
